### ISSUE TITLE
New Listing Carousel Component

### ISSUE THREAD

**Issue by geekysilento** [DevsThatMatter/nksm#24]

**Comment by heydoyouknowme0** [comment]
#18

**Comment by aryansri-19** [comment]
we need arrows for navigation or just mouse click and slide? @geekysilento @som-04 @heydoyouknowme0

**Comment by geekysilento** [comment]
scroll inside the carousel to slide and arrows

**Comment by heydoyouknowme0** [comment]
https://www.embla-carousel.com/plugins/wheel-gestures/
