### ISSUE TITLE
Optimize Category icons for smaller screens

### ISSUE THREAD

**Issue by geekysilento** [DevsThatMatter/nksm#6]
![image](https://github.com/DevsThatMatter/nksm/assets/125768789/477b6807-68b2-4249-85a9-1a04bd4e9d1e)

make every card smaller by 20%

inspiration: [walmart.com](https://www.walmart.com/)

**Comment by aryansri-19** [comment]
![image](https://github.com/DevsThatMatter/nksm/assets/75990590/86abc575-84cb-4e9e-bcb8-ce7fe15a1d0f)
how's this?
