### ISSUE TITLE
Error disables Ssr

### ISSUE THREAD

**Issue by heydoyouknowme0** [DevsThatMatter/nksm#7]
Not just a simple error, please fix

![image](https://github.com/DevsThatMatter/nksm/assets/68548165/19e360b9-dc99-457f-92f0-47902d019c4c)

**Comment by aryansri-19** [comment]
Error fixed, SheetTrigger is itself a button, dont need to add button inside it.
![image](https://github.com/DevsThatMatter/nksm/assets/75990590/79fbb6b3-7b5f-498d-956b-3179ff7919e7)

**Comment by aryansri-19** [comment]
Fixed finally
